steps:
  - bash: |
      set -e
      curl -Os https://cli.codecov.io/latest/linux/codecov
      chmod +x codecov
      echo "Starting Codecov Upload"
      ./codecov --verbose upload-process  -t $(codecov-token)
    retryCountOnTaskFailure: 1
    displayName: Upload Coverage Report To Codecov.io
    condition: succeededOrFailed()
